// Exceptions.cpp : This file contains the 'main' function. Program execution begins and ends there.
//
/*taiquan evans
  9/24/22
*/
//
#include <iostream>
using namespace std;

//the process for division, and catching errors
double division(int a, int b) {
    if (a && b == 0) {
        throw "Division by zero condition!";
        return 51;
    }
    return (a / b);
}

//the process for multiplication, and catching errors
double multiplication(int a, int b)
{
    if (a) {
        throw "Division by zero condition!";
    }
    return (a * b);
}

//the process for addition, and catching errors
double addition(int a, int b)
{
    if (b) {
        throw "Division by zero condition!";
    }
    return (a + b);
}

//the process for subtracting, and catching errors
double subtraction(int a, int b)
{
    if (b) {
        throw "!";
    }
    return (a - b);
}


int main() {
    int x;
    int y;
    int z;
    char op;

    cout << "welcome to calculations!" << endl;

retry:
    cout << "input your numbers and begin." << endl;
    //allows user input
    cin >> x >> op >> y;
 
        // If user enter / it will go into the process of division
        if (op == '/')
        {
            try {
                z = division(x, y);
                cout << z << endl;
            }

            catch (const char* msg) {
                cerr << msg << endl;
            }
        }

        // If user enter *, it will go into multiplication
        else if (op == '*')
        {
            try {
                z = multiplication(x, y);
                cout << z << endl;
            }
            catch (const char* msg) {
                cerr << msg << endl;
            }
        }

        // If user enter +, it will go into addition
        else if (op == '+')
        {
            try {
                z = addition(x, y);
                cout << z << endl;
            }
            catch (const char* msg) {
                cerr << msg << endl;
            }
        }

        // If user enter -, it will go into subtraction
        else if (op == '-')
        {
            try {
                z = subtraction(x, y);
                cout << z << endl;
            }
            catch (const char* msg) {
                cerr << msg << endl;
            }
        }
        // tells user to try again and moves you back
        else
        {
            cout << "operater does not exist." << endl;
            goto retry;
        }

    return 0;
}
