// Exceptions.cpp : This file contains the 'main' function. Program execution begins and ends there.
//
/*taiquan evans
  9/24/22
*/
#include <iostream>
using namespace std;

double division(int a, int b) {
    if (b == 0) {
        throw "Division by zero condition!";
    }
    return (a / b);
}

double multiplication(int a, int b)
{

}


int main() {
    int x;
    int y;
    int z;

    try {
        z = division(x, y);
        cout << z << endl;
    }
 
    catch (const char* msg) {
        cerr << msg << endl;
    }

   try {
       z = multiplication(x, y);
            cout << z << endl;
    }
   catch (const char* msg) {
       cerr << msg << endl;
   }

    return 0;
}
